### ISSUE TITLE
Replace mvstore with SQLite

### ISSUE THREAD

**Issue by io7m** [io7m-com/looseleaf#11]

**Comment by io7m** [comment]
In local testing, even with WAL mode and all of the concurrency-friendly options turned on, concurrency seems significantly worse than MVStore. For the smoke tests, 20% of requests fail with SQLite whereas less than 2% fail with MVStore on the same workload. The symptom is always the same `SQLITE_BUSY` error code.

**Comment by io7m** [comment]
This seems to be down to multi-thread access. Serializing access to the database with a semaphore greatly increases throughput, and eliminates the `SQLITE_BUSY` errors. It remains to be seen whether this is any better than `mvstore` or not.

**Comment by io7m** [comment]
It will prevent future instances of this kind of problem:

```
May 20 20:03:24 control1.io7m.com looseleaf[8610]: org.h2.mvstore.MVStoreException: The write format 2 is smaller than the supported format 3 [2.2.224/5]
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.h2database.mvstore@2.2.224/org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.h2database.mvstore@2.2.224/org.h2.mvstore.FileStore.getUnsupportedWriteFormatException(FileStore.java:943)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.h2database.mvstore@2.2.224/org.h2.mvstore.FileStore.processCommonHeaderAttributes(FileStore.java:547)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.h2database.mvstore@2.2.224/org.h2.mvstore.RandomAccessStore.readStoreHeader(RandomAccessStore.java:227)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.h2database.mvstore@2.2.224/org.h2.mvstore.FileStore.start(FileStore.java:916)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.h2database.mvstore@2.2.224/org.h2.mvstore.MVStore.<init>(MVStore.java:289)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.h2database.mvstore@2.2.224/org.h2.mvstore.MVStore.open(MVStore.java:391)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.io7m.looseleaf.database.mvstore@2.0.0/com.io7m.looseleaf.database.mvstore.LLDatabaseMVStoreFactory.open(LLDatabaseMVStoreFactory.java:52)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.io7m.looseleaf.server@2.0.0/com.io7m.looseleaf.server.LLServers.open(LLServers.java:139)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.io7m.looseleaf.cmdline@2.0.0/com.io7m.looseleaf.cmdline.internal.LLServer.onExecute(LLServer.java:94)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.io7m.quarrel.core@1.6.1/com.io7m.quarrel.core.internal.QCommandContext.execute(QCommandContext.java:207)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.io7m.quarrel.core@1.6.1/com.io7m.quarrel.core.QApplicationType.run(QApplicationType.java:94)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.io7m.looseleaf.cmdline@2.0.0/com.io7m.looseleaf.cmdline.Main.run(Main.java:119)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.io7m.looseleaf.cmdline@2.0.0/com.io7m.looseleaf.cmdline.Main.mainExitless(Main.java:103)
May 20 20:03:24 control1.io7m.com looseleaf[8610]:   at com.io7m.looseleaf.cmdline@2.0.0/com.io7m.looseleaf.cmdline.Main.main(Main.java:88)
```

The SQLite format is very stable.
